### ISSUE TITLE
Cant generate reports java 17 and JMeter 5.6.3

### ISSUE THREAD

**Issue by cristian-moreno-mimacom** [qualersoft/jmeter-gradle-plugin#214]
**Describe the bug**
When trying to generate reports via gradle I'm getting the following error: 

`2024-03-07 09:25:51,912 INFO o.a.j.r.p.NormalizerSampleConsumer: Using format, 'ms', to parse timeStamp field
2024-03-07 09:25:52,121 INFO o.a.j.r.p.AbstractSampleConsumer: class org.apache.jmeter.report.processor.AggregateConsumer#stopProducing(): beginDate produced 0 samples
2024-03-07 09:25:52,121 INFO o.a.j.r.p.AbstractSampleConsumer: class org.apache.jmeter.report.processor.AggregateConsumer#stopProducing(): endDate produced 0 samples
2024-03-07 09:25:52,123 INFO o.a.j.r.p.AbstractSampleConsumer: class org.apache.jmeter.report.processor.ApdexSummaryConsumer#stopProducing(): apdexSummary produced 0 samples
2024-03-07 09:25:52,123 INFO o.a.j.r.p.AbstractSampleConsumer: class org.apache.jmeter.report.processor.RequestsSummaryConsumer#stopProducing(): requestsSummary produced 0 samples
2024-03-07 09:25:52,129 INFO o.a.j.r.p.AbstractSampleConsumer: class org.apache.jmeter.report.processor.StatisticsSummaryConsumer#stopProducing(): statisticsSummary produced 0 samples
2024-03-07 09:25:52,132 ERROR o.a.j.JMeter: Error generating the report: Error while processing samples: Consumer failed with message :Consumer failed with message :Consumer failed with message :Consumer failed with message :Begin size 0 is not equal to fixed size 5
org.apache.jmeter.report.dashboard.GenerationException: Error while processing samples: Consumer failed with message :Consumer failed with message :Consumer failed with message :Consumer failed with message :Begin size 0 is not equal to fixed size 5
	at org.apache.jmeter.report.dashboard.ReportGenerator.generate(ReportGenerator.java:242) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.JMeter$ListenToTest.endTest(JMeter.java:1346) [ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.JMeter$ListenToTest.testEnded(JMeter.java:1301) [ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218) [ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:493) [ApacheJMeter_core-5.4.1.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.apache.jmeter.report.core.SampleException: Consumer failed with message :Consumer failed with message :Consumer failed with message :Consumer failed with message :Begin size 0 is not equal to fixed size 5
	at org.apache.jmeter.report.processor.CsvFileSampleSource$PrivateProducer.stopProducing(CsvFileSampleSource.java:338) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource.produce(CsvFileSampleSource.java:182) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource.run(CsvFileSampleSource.java:235) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.dashboard.ReportGenerator.generate(ReportGenerator.java:240) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	... 5 more
Caused by: org.apache.jmeter.report.core.SampleException: Consumer failed with message :Consumer failed with message :Consumer failed with message :Begin size 0 is not equal to fixed size 5
	at org.apache.jmeter.report.processor.AbstractSampleConsumer.stopProducing(AbstractSampleConsumer.java:244) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.NormalizerSampleConsumer.stopConsuming(NormalizerSampleConsumer.java:125) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource$PrivateProducer.stopProducing(CsvFileSampleSource.java:335) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource.produce(CsvFileSampleSource.java:182) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource.run(CsvFileSampleSource.java:235) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.dashboard.ReportGenerator.generate(ReportGenerator.java:240) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	... 5 more
Caused by: org.apache.jmeter.report.core.SampleException: Consumer failed with message :Consumer failed with message :Begin size 0 is not equal to fixed size 5
	at org.apache.jmeter.report.processor.AbstractSampleConsumer.stopProducing(AbstractSampleConsumer.java:244) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.FilterConsumer.stopConsuming(FilterConsumer.java:111) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.AbstractSampleConsumer.stopProducing(AbstractSampleConsumer.java:241) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.NormalizerSampleConsumer.stopConsuming(NormalizerSampleConsumer.java:125) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource$PrivateProducer.stopProducing(CsvFileSampleSource.java:335) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource.produce(CsvFileSampleSource.java:182) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource.run(CsvFileSampleSource.java:235) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.dashboard.ReportGenerator.generate(ReportGenerator.java:240) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	... 5 more
Caused by: org.apache.jmeter.report.core.SampleException: Consumer failed with message :Begin size 0 is not equal to fixed size 5
	at org.apache.jmeter.report.processor.AbstractSampleConsumer.stopProducing(AbstractSampleConsumer.java:244) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.FilterConsumer.stopConsuming(FilterConsumer.java:111) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.AbstractSampleConsumer.stopProducing(AbstractSampleConsumer.java:241) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.FilterConsumer.stopConsuming(FilterConsumer.java:111) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.AbstractSampleConsumer.stopProducing(AbstractSampleConsumer.java:241) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.NormalizerSampleConsumer.stopConsuming(NormalizerSampleConsumer.java:125) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource$PrivateProducer.stopProducing(CsvFileSampleSource.java:335) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource.produce(CsvFileSampleSource.java:182) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource.run(CsvFileSampleSource.java:235) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.dashboard.ReportGenerator.generate(ReportGenerator.java:240) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	... 5 more
Caused by: java.lang.IllegalStateException: Begin size 0 is not equal to fixed size 5
	at java.util.stream.Nodes$FixedNodeBuilder.begin(Nodes.java:1214) ~[?:?]
	at java.util.stream.Sink$ChainedReference.begin(Sink.java:253) ~[?:?]
	at java.util.stream.SliceOps$1$1.begin(SliceOps.java:192) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:354) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:528) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at org.apache.jmeter.report.processor.Top5ErrorsSummaryData.getTop5ErrorsMetrics(Top5ErrorsSummaryData.java:82) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.Top5ErrorsBySamplerConsumer.createDataResult(Top5ErrorsBySamplerConsumer.java:97) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.Top5ErrorsBySamplerConsumer.createDataResult(Top5ErrorsBySamplerConsumer.java:29) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.AbstractSummaryConsumer.createResultFromKey(AbstractSummaryConsumer.java:200) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.AbstractSummaryConsumer.stopConsuming(AbstractSummaryConsumer.java:261) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.AbstractSampleConsumer.stopProducing(AbstractSampleConsumer.java:241) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.FilterConsumer.stopConsuming(FilterConsumer.java:111) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.AbstractSampleConsumer.stopProducing(AbstractSampleConsumer.java:241) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.FilterConsumer.stopConsuming(FilterConsumer.java:111) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.AbstractSampleConsumer.stopProducing(AbstractSampleConsumer.java:241) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.NormalizerSampleConsumer.stopConsuming(NormalizerSampleConsumer.java:125) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource$PrivateProducer.stopProducing(CsvFileSampleSource.java:335) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource.produce(CsvFileSampleSource.java:182) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.processor.CsvFileSampleSource.run(CsvFileSampleSource.java:235) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	at org.apache.jmeter.report.dashboard.ReportGenerator.generate(ReportGenerator.java:240) ~[ApacheJMeter_core-5.4.1.jar:5.4.1]
	... 5 more`

**To Reproduce**
1.
`import de.qualersoft.jmeter.gradleplugin.task.JMeterRunTask
tasks.register("runJMeter-DEV", JMeterRunTask) {

    jmeter {
        jvmArgs.add("-Xms2g")
        jvmArgs.add("-Xmx2g")
        jvmArgs.add("-XX:MaxMetaspaceSize=512m")

        maxHeap.set("3g")

        tool {
            version = "5.6.3"
        }
    }
    jmxFile.set("Test.jmx")
    generateReport = true
}`
2. ./gradlew runJMeter-DEV --info --stacktrace
3. ![image](https://github.com/qualersoft/jmeter-gradle-plugin/assets/133767193/eb334199-d9ce-4da6-92b6-81d1e9e04708)

**Expected behavior**
Report generated and created under build/resports/jmeter, at present appearing empty.

**Data/Screenshots**
[jmeter.log](https://github.com/qualersoft/jmeter-gradle-plugin/files/14521304/jmeter.log)

**System (please complete the following information):**
- OS: Windows
- OS-Version: 11 Pro
- Gradle-Version: Gradle 8.4
- Plugin-Version: 2.4.0

**Additional context**
JVM:          17.0.7 (OpenLogic 17.0.7+7-adhoc..jdk17u)

**Comment by mathze** [comment]
This seems to be a regression in jmeter itself please refer to #149 or #178.
As a workaround until they fixed it, you could either downgrade java version or jmeter.

**Comment by cristian-moreno-mimacom** [comment]
Thanks mate!, but with the 5.5 and 5.6 version of JMeter and our current version of JVM is not resolving the issue. Stills appearing the error when generating the report. Also we cannot downgrade our JVM version.
