### ISSUE TITLE
`jmeterGui` task fails when dependent task `setupJMeter` is skipped due to up-to-date check.

### ISSUE THREAD

**Issue by mricciuti** [qualersoft/jmeter-gradle-plugin#48]
**Describe the bug**
When executing JMeter GUI task a second time after a first execution, the task fails with error message:
```
Execution failed for task ':jmeterGui'.
> Cannot query the value of task ':setupJMeter' property 'jmJar$jmeter_gradle_plugin' because it has no value available.
```
This seems to be a regression in release 2.3.0 after implementation of enhancement https://github.com/qualersoft/jmeter-gradle-plugin/issues/44

I think that the `jmJar` property is not properly set anymore when `setupJMeter` is not executed (in case of positive up-to-date check, for example)

A workaround is to force `setupJMeter` task to always be executed ( `setupJMeter.outputs.upToDateWhen { false }` ), but this goes against the aim of enhancement  #44

**To Reproduce**
1. execute gradle task `jmeterGui`
2. execute gradle task `jmeterGui` a second time, without performing `gradle clean` between both executions
3. See error

**Expected behavior**
The task `jmeterGui` should execute normally event when when `setupJmeter` tasks is up-to-date

**Data/Screenshots**
Gradle logs:

- first execution of `jmeterGui` task
```
18:26:58: Executing 'jmeterGui'...

> Configure project   
> Task :setupJMeter
> Task :jmeterGui
================================================================================
Don't use GUI mode for load testing !, only for Test creation and Test debugging.
[.... ]
```
- second execution attempt: 
```
18:30:00: Executing 'jmeterGui'...

> Task :setupJMeter UP-TO-DATE
> Task :jmeterGui FAILED
8 actionable tasks: 1 executed, 7 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jmeterGui'.
> Cannot query the value of task ':setupJMeter' property 'jmJar$jmeter_gradle_plugin' because it has no value available.
Caused by: org.gradle.api.internal.provider.MissingValueException: Cannot query the value of task ':setupJMeter' property 'jmJar$jmeter_gradle_plugin' because it has no value available.
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:86)
	at de.qualersoft.jmeter.gradleplugin.task.JMeterBaseTask.jmToolJar$lambda-0(JMeterBaseTask.kt:170)
	at org.gradle.api.internal.provider.TransformBackedProvider.mapValue(TransformBackedProvider.java:73)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:65)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
	at org.gradle.api.internal.provider.MappingProvider.calculateOwnValue(MappingProvider.java:55)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
	at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:128)
	at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:26)
	at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:133)
	at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:127)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:84)
	at de.qualersoft.jmeter.gradleplugin.task.JMeterBaseTask.exec(JMeterBaseTask.kt:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**System (please complete the following information):**
- OS:  Windows
- OS-Version: 11
- Gradle-Version: 7.4
- Plugin-Version: 2.3.0

**Comment by mricciuti** [comment]
Hi @mathze ,
At first sight, problem is coming from this  https://github.com/qualersoft/jmeter-gradle-plugin/blob/v2.2.0/src/main/kotlin/de/qualersoft/jmeter/gradleplugin/task/JMeterSetupTask.kt#L42

the `jmJar` property is referenced and used by all tasks from `JMeterBaseTask.exec()` main method, but its value is set in `JMeterSetupTask.run()` which is executed only if setup task is executed , so not when setup task is up-to-date.
maybe you should leave this property initialization code out of the `@TaskAction` method, so that it's executed in gradle configuration phase, not in execution phase.
